<?php

/**
 ****************************************************
 * countries.class.php                              *
 ****************************************************
 * Angora Guestbook                                 *
 ****************************************************
 * Software author :            Adel Noureddine     *
 * Copyright 2005 - 2009 by :   Adel Noureddine     *
 ****************************************************
 * The countries class file                         *
 ****************************************************
 * */

class Countries {
	
	private $countriesArray = array(
		"00" => "Unkown",
		"ac" => "Ascension Islands",
		"ad" => "Andorra",
		"ae" => "United Arab Emirates",
		"af" => "Afghanistan",
		"ag" => "Antigua and Barbuda",
		"al" => "Albania",
		"am" => "Armenia",
		"ao" => "Angola",
		"ar" => "Argentina",
		"at" => "Austria",
		"au" => "Australia",
		"az" => "Azerbaijan",
		"ba" => "Bosnia and Herzegovina",
		"bb" => "Barbados",
		"bd" => "Bangladesh",
		"be" => "Belgium",
		"bf" => "Burkina Faso",
		"bg" => "Bulgaria",
		"bh" => "Bahrain",
		"bi" => "Burundi",
		"bj" => "Benin",
		"bn" => "Bruneo",
		"bo" => "Bolivia",
		"br" => "Brazil",
		"bs" => "Bahamas",
		"bt" => "Bhutan",
		"bw" => "Botswana",
		"by" => "Belarus",
		"bz" => "Belize",
		"ca" => "Canada",
		"cd" => "Congo",
		"cf" => "Central African Republic",
		"ch" => "Switzerland",
		"ci" => "Cote D'Ivoire",
		"ck" => "Cook Islands",
		"cl" => "Chile",
		"cm" => "Cameroon",
		"cn" => "China",
		"co" => "Colombia",
		"cr" => "Costa Rica",
		"cs" => "Serbia",
		"cu" => "Cuba",
		"cy" => "Cyprus",
		"cz" => "Czech Republic",
		"de" => "Germany",
		"dj" => "Djibouti",
		"dk" => "Denmark",
		"dm" => "Dominica",
		"do" => "Dominican Republic",
		"dz" => "Algeria",
		"ec" => "Ecuador",
		"ee" => "Estonia",
		"eg" => "Egypt",
		"er" => "Eritrea",
		"es" => "Spain",
		"et" => "Ethiopia",
		"fi" => "Finland",
		"fj" => "Fiji",
		"fm" => "Micronesia",
		"fr" => "France",
		"ga" => "Gabon",
		"gd" => "Grenada",
		"ge" => "Georgia",
		"gh" => "Ghana",
		"gm" => "Gambia",
		"gn" => "Guinea",
		"gq" => "Equatorial Guinea",
		"gr" => "Greece",
		"gt" => "Guatemala",
		"gw" => "Guinea-Bissau",
		"gy" => "Guyana",
		"hn" => "Honduras",
		"hr" => "Croatia",
		"ht" => "Haiti",
		"hu" => "Hungary",
		"id" => "Indonesia",
		"ie" => "Ireland",
		"il" => "Israel",
		"in" => "India",
		"iq" => "Iraq",
		"ir" => "Iran",
		"is" => "Iceland",
		"it" => "Italy",
		"jm" => "Jamaica",
		"jo" => "Jordan",
		"jp" => "Japan",
		"ke" => "Kenya",
		"kg" => "Kyrgyzstan",
		"kh" => "Cambodia",
		"km" => "Comoros",
		"kp" => "North Korea",
		"kr" => "South Korea",
		"kw" => "Kuwait",
		"kz" => "Kazakhstan",
		"la" => "Laos",
		"lb" => "Lebanon",
		"lc" => "Saint Lucia",
		"li" => "Liechtenstein",
		"lk" => "Sri Lanka",
		"lr" => "Liberia",
		"ls" => "Lesotho",
		"lt" => "Lithuania",
		"lu" => "Luxembourg",
		"lv" => "Latvia",
		"ly" => "Libya",
		"ma" => "Morocco",
		"mc" => "Monaco",
		"md" => "Moldova",
		"mg" => "Madagascar",
		"mk" => "Macedonia",
		"ml" => "Mali",
		"mm" => "Myanmar",
		"mn" => "Mongolia",
		"mr" => "Mauritania",
		"mt" => "Malta",
		"mv" => "Maldives",
		"mw" => "Malawi",
		"mx" => "Mexico",
		"my" => "Malaysia",
		"mz" => "Mozambique",
		"na" => "Namibia",
		"ne" => "Niger",
		"ng" => "Nigeria",
		"ni" => "Nicaragua",
		"nl" => "Netherlands",
		"no" => "Norway",
		"np" => "Nepal",
		"nr" => "Nauru",
		"nu" => "Niue",
		"nz" => "New Zealand",
		"om" => "Oman",
		"pa" => "Panama",
		"pe" => "Peru",
		"pg" => "Papua New Guinea",
		"ph" => "Philippines",
		"pk" => "Pakistan",
		"pl" => "Poland",
		"ps" => "Palestine",
		"pt" => "Portugal",
		"pw" => "Palau",
		"py" => "Paraguay",
		"qa" => "Qatar",
		"ro" => "Romania",
		"ru" => "Russia",
		"rw" => "Rwanda",
		"sa" => "Saudi Arabia",
		"sb" => "Solomon Islands",
		"sc" => "Seychelles",
		"sd" => "Sudan",
		"se" => "Sweden",
		"sg" => "Singapore",
		"si" => "Slovenia",
		"sk" => "Slovakia",
		"sl" => "Sierra Leone",
		"sm" => "San Marino",
		"sn" => "Senegal",
		"so" => "Somalia",
		"sr" => "Suriname",
		"st" => "Sao Tome and Principe",
		"sv" => "El Salvador",
		"sy" => "Syria",
		"sz" => "Switzerland",
		"td" => "Chad",
		"tg" => "Togo",
		"th" => "Thailand",
		"tj" => "Tajikistan",
		"tl" => "East Timor",
		"tm" => "Turkmenistan",
		"tn" => "Tunisia",
		"to" => "Tonga",
		"tr" => "Turkey",
		"tt" => "Trinidad and Tobago",
		"tv" => "Tuvalu",
		"tw" => "Taiwan",
		"tz" => "Tanzania",
		"ua" => "Ukraine",
		"ug" => "Uganda",
		"uk" => "United Kingdom",
		"us" => "United States of America",
		"uy" => "Uruguay",
		"uz" => "Uzbekistan",
		"va" => "Vatican City",
		"vc" => "Saint Vincent and the Grenadines",
		"ve" => "Venezuela",
		"vn" => "Vietnam",
		"vu" => "Vanuatu",
		"ws" => "Samoa",
		"ye" => "Yemen",
		"za" => "South Africa",
		"zm" => "Zambia",
		"zr" => "Zaire",
		"zw" => "Zimbabwe",
	);
	
	function __construct() {
	}
	
	function __destruct() {
		unset($this->countriesArray);
	}
	
	function getCountry($countryCode) {
		return $this->countriesArray[$countryCode];
	}
	
	function getCountriesArray() {
		$arrayReturn = array_unique($this->countriesArray);
		asort($arrayReturn);
		return $arrayReturn;
	}
	
}

?>